# Generated by Django 4.0.5 on 2022-06-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_alphagram_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='hash',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
