# Generated by Django 4.0.5 on 2022-06-06 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_corpus_alphagram_delete_alphagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_chain', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='corpus',
            name='alphagram',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.alphagram'),
            preserve_default=False,
        ),
    ]
