# Generated by Django 4.0.5 on 2022-06-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alphagram_corpus_alphagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='alphagram',
        ),
        migrations.DeleteModel(
            name='Alphagram',
        ),
    ]
