# Generated by Django 4.0.5 on 2022-06-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_corpus_alphagram_delete_alphagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='word',
            field=models.CharField(max_length=63),
        ),
    ]
