# Generated by Django 4.0.5 on 2022-06-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_corpus_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='word',
            field=models.CharField(max_length=70),
        ),
    ]
